# Use an official lightweight Python image
FROM python:3.13

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . /app/

# Expose port 5000
EXPOSE 5000

# Run the Flask app
CMD ["python", "app.py"]
